### ISSUE TITLE
Error in makefile on R Pi5

### ISSUE THREAD

**Issue by tony1tf** [Rhizomatica/hermes-net#1]
make -C trx_v2-userland
make[1]: Entering directory '/home/pi/hermes-net/trx_v2-userland'
gcc -c `pkg-config --cflags gtk+-3.0` -O3 -funroll-loops -march=armv8-a+crc -moutline-atomics -Wall -Wno-deprecated-declarations -std=gnu11 -pthread -DMG_ENABLE_OPENSSL -DMG_ARCH=1 vfo.c -o vfo.o
gcc: error: unrecognized command-line option ‘-moutline-atomics’; did you mean ‘-finline-atomics’?
make[1]: *** [Makefile:46: vfo.o] Error 1
make[1]: Leaving directory '/home/pi/hermes-net/trx_v2-userland'
make: *** [Makefile:34: trx_v2-userland] Error 2

**Comment by rafael2k** [comment]
Hi Tony. Which Linux architecture and distribution version are you using?

**Comment by tony1tf** [comment]
Bookworm 64 bit

**Comment by rafael2k** [comment]
Tony, try to open the Makefile and just remove "-moutline-atomics". I'm doing a re-write in trx_v3-userland directory. trx_v2 is raspberry pi 4 only and I did not really test on bookworm.

**Comment by tony1tf** [comment]
PRETTY_NAME="Raspbian GNU/Linux 12 (bookworm)"
NAME="Raspbian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by rafael2k** [comment]
Are you using the Pi 4 or Pi 5?

**Comment by tony1tf** [comment]
Pi 5 - our Hackspace got an early one by agreeing to host a Raspberry Pi
event, and I want to demo ham radio with it.
Tony
G3OVH

**Comment by rafael2k** [comment]
The only software I already moved to gpiolib (which supports Pi 5 is):
https://github.com/Rhizomatica/sbitx-core
and
https://github.com/Rhizomatica/hermes-net/tree/main/trx_v3-userland

**Comment by tony1tf** [comment]
I don't see the command yet for V3 on hermes-net
Also. I can't find where -moutline.... is used

Tony

**Comment by tony1tf** [comment]
Aha - I think I see - do I have to go down to the V3 directory and use the
make file there, rather than the top level hermes-net makefile?

**Comment by tony1tf** [comment]
I've tried compiling V3 and removing the -moutline4-atomics option.
Now I have another error:
cc1: error: ‘-mfloat-abi=hard’: selected architecture lacks an FPU

**Comment by rafael2k** [comment]
This compile flag is not in the Makefile. I'm not sure exactly you are doing are what do you expect from the software.

**Comment by rafael2k** [comment]
If you want to port Farhan's sbitx, I can give some guidance.

**Comment by tony1tf** [comment]
I can't deal with errors that I dont have the knowledge to fix.
I'll wait till everything settles down on your git page. I would presume that I will do a git clone of hermes-net, and make from there to get code to drive a V3 board (which I will only be simulating).
So guidance on how to port Farhan's sbitx code would be great, thank you.

**Comment by tony1tf** [comment]
Hi Rafael

Sorry - simulating is too specific a term - what I meant is that I don't
yet have an sbitx board, and I want to use the software to experiment with
parts of a transceiver. I was going to look at the Hermes code and see
where you had converted Farhan's code to work without needing WiringPi so I
can run it on a Pi5. I also have older Pi's so should be able to run
Farhan's code directly, but I wanted to demo the Pi5 at an exhibition in a
couple of months as our Hackspace got a free one from the R Pi foundation.
I looked at your WiringPi source code, and it is very complex in the way it
has to cater for every Pi since the model A, so it is best avoided if there
are simpler alternatives.
What's the best tools to use (rather than mark 1 eyeballs) for finding the
places to change the gpio calls?
I am a retired electronic engineer, not a software programmer, so forgive
my ignorance!

Tony

**Comment by rafael2k** [comment]
Hi Tony, sorry, but it makes no sense for me what you are doing. If you want to simulation, take a look in GnuRadio and its gnuradio-companion software.

**Comment by tony1tf** [comment]
Hi Rafael

As I said, simulation was the wrong word - I meant experimenting with
variations in hardware with real hardware, but need to be able to modify
the software that controls it.
I know there's lots of ways to use software systems to emulate hardware - I
regularly use LTSpice to simulate valve (tube) based chassis that we use
for a 1949 computer rebuild at the National Museum of Computing, UK. It
saves me having to cut holes in a chassis to take more valve bases!

Tony

**Comment by rafael2k** [comment]
Tony, start with this one:
https://github.com/Rhizomatica/sbitx-core
Fetch gpiolib branch:
https://github.com/Rhizomatica/sbitx-core/tree/gpiolib
